<?php

namespace Ppecheny\QuestionaryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAnswerRepository extends EntityRepository
{
}
